# Generated by Django 2.2.7 on 2019-12-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=255)),
                ('admin_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Class_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_video', models.CharField(max_length=255)),
                ('detail_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Class_lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_img', models.CharField(max_length=255)),
                ('list_name', models.CharField(max_length=50)),
                ('list_text', models.CharField(max_length=255)),
                ('list_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Class_top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_img', models.CharField(max_length=255)),
            ],
        ),
    ]
